# Generated by Django 2.1 on 2019-12-04 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parent', models.ManyToManyField(blank=True, related_name='_artist_parent_+', to='ekimei1.Artist', verbose_name='所属グループ等')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_cd', models.IntegerField(default=0, unique=True)),
                ('company_cd', models.IntegerField(default=0)),
                ('line_name', models.CharField(max_length=200)),
                ('line_name_k', models.CharField(blank=True, max_length=200, null=True)),
                ('line_name_h', models.CharField(blank=True, max_length=200, null=True)),
                ('line_color_c', models.CharField(blank=True, max_length=200, null=True)),
                ('line_color_t', models.CharField(blank=True, max_length=200, null=True)),
                ('line_type', models.CharField(blank=True, max_length=200, null=True)),
                ('lon', models.CharField(blank=True, max_length=200, null=True)),
                ('lat', models.CharField(blank=True, max_length=200, null=True)),
                ('zoom', models.IntegerField(default=0)),
                ('e_status', models.IntegerField(default=0)),
                ('e_sort', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='動画タイトル')),
                ('main_id', models.CharField(max_length=200, unique=True, verbose_name='動画ID')),
                ('youtube_id', models.CharField(blank=True, max_length=200, verbose_name='YouTubeのID')),
                ('niconico_id', models.CharField(blank=True, max_length=200, verbose_name='ニコニコ動画のID')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='投稿日時')),
                ('duration', models.DurationField(null=True, verbose_name='動画の長さ')),
                ('n_view', models.IntegerField(blank=True, default=0, verbose_name='再生回数')),
                ('n_like', models.IntegerField(blank=True, default=0, verbose_name='高評価数')),
                ('n_dislike', models.IntegerField(blank=True, default=0, verbose_name='低評価数')),
                ('n_comment', models.IntegerField(blank=True, default=0, verbose_name='コメント数')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('reg_date', models.DateTimeField(blank=True, verbose_name='データベース登録日時')),
                ('is_collab', models.CharField(choices=[('S', '単作'), ('C', '合作')], default='S', max_length=1, verbose_name='合作か')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekimei1.Category', verbose_name='カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_num', models.IntegerField()),
                ('part_name_short', models.CharField(max_length=5)),
                ('part_name', models.CharField(max_length=200)),
                ('start_time', models.DurationField(null=True, verbose_name='開始時間')),
                ('song_name', models.CharField(max_length=200)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekimei1.Movie', to_field='main_id')),
                ('participant', models.ManyToManyField(blank=True, to='ekimei1.Name', verbose_name='参加名義')),
            ],
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_cd', models.IntegerField(default=0)),
                ('pref_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='曲名')),
                ('namerb', models.CharField(blank=True, max_length=200, verbose_name='曲名カナ')),
                ('album', models.CharField(blank=True, max_length=200, verbose_name='アルバム名')),
                ('lyrist', models.CharField(blank=True, max_length=200, verbose_name='作詞者')),
                ('composer', models.CharField(blank=True, max_length=200, verbose_name='作曲者')),
                ('tieup', models.CharField(blank=True, max_length=200, verbose_name='タイアップ等')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='備考')),
                ('artist', models.ManyToManyField(blank=True, to='ekimei1.Artist')),
                ('parent', models.ManyToManyField(blank=True, related_name='_song_parent_+', to='ekimei1.Song', verbose_name='原作等')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_cd', models.IntegerField(default=0, unique=True, verbose_name='駅コード')),
                ('station_g_cd', models.IntegerField(default=0, verbose_name='駅グループコード')),
                ('station_name', models.CharField(max_length=200, verbose_name='駅名')),
                ('station_name_k', models.CharField(blank=True, max_length=200, null=True, verbose_name='駅名(カナ)')),
                ('station_name_r', models.CharField(blank=True, max_length=200, null=True, verbose_name='駅名(ローマ字)')),
                ('post', models.CharField(blank=True, max_length=200, null=True, verbose_name='駅郵便番号')),
                ('add', models.CharField(blank=True, max_length=200, null=True, verbose_name='住所')),
                ('lon', models.CharField(blank=True, max_length=200, null=True, verbose_name='経度')),
                ('lat', models.CharField(blank=True, max_length=200, null=True, verbose_name='緯度')),
                ('open_ymd', models.DateField(blank=True, max_length=200, null=True, verbose_name='開業年月日')),
                ('close_ymd', models.DateField(blank=True, max_length=200, null=True, verbose_name='廃止年月日')),
                ('e_status', models.IntegerField(choices=[(0, '運用中'), (1, '運用前'), (2, '廃止')], default=0, verbose_name='状態')),
                ('e_sort', models.IntegerField(default=0, verbose_name='並び順')),
                ('line_cd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ekimei1.Line', to_field='line_cd', verbose_name='路線')),
                ('pref_cd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekimei1.Prefecture', verbose_name='都道府県')),
            ],
        ),
        migrations.CreateModel(
            name='StationInMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_movie', models.IntegerField()),
                ('station_name', models.CharField(max_length=200)),
                ('non_line', models.BooleanField(default=False, verbose_name='路線不定')),
                ('back_rel', models.IntegerField(default=1, verbose_name='前駅との関係')),
                ('movie_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekimei1.Part')),
                ('station_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekimei1.Station', to_field='station_cd')),
            ],
        ),
        migrations.CreateModel(
            name='Vocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ボーカル名')),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeChannel',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('channelId', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='song',
            field=models.ManyToManyField(blank=True, to='ekimei1.Song', verbose_name='使用楽曲'),
        ),
        migrations.AddField(
            model_name='part',
            name='vocal',
            field=models.ManyToManyField(blank=True, to='ekimei1.Vocal', verbose_name='使用ボーカル'),
        ),
        migrations.AddField(
            model_name='movie',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekimei1.YoutubeChannel', verbose_name='投稿チャンネル'),
        ),
        migrations.AddField(
            model_name='movie',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='_movie_parent_+', to='ekimei1.Movie', verbose_name='親作品'),
        ),
        migrations.AddField(
            model_name='movie',
            name='participant',
            field=models.ManyToManyField(blank=True, to='ekimei1.Name', verbose_name='参加者'),
        ),
        migrations.AddField(
            model_name='movie',
            name='song',
            field=models.ManyToManyField(blank=True, to='ekimei1.Song', verbose_name='使用楽曲'),
        ),
        migrations.AddField(
            model_name='movie',
            name='vocal',
            field=models.ManyToManyField(blank=True, to='ekimei1.Vocal', verbose_name='使用ボーカル'),
        ),
        migrations.AddField(
            model_name='line',
            name='pref_cds',
            field=models.ManyToManyField(blank=True, to='ekimei1.Prefecture'),
        ),
    ]
