# Generated by Django 2.1 on 2019-12-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekimei1', '0002_auto_20191204_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='start_time',
            field=models.DurationField(blank=True, null=True, verbose_name='開始時間'),
        ),
    ]
