# Generated by Django 2.1 on 2019-12-04 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekimei1', '0003_auto_20191204_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_name', to='ekimei1.Creator', verbose_name='作者'),
        ),
    ]
