# Generated by Django 2.1 on 2019-12-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekimei1', '0004_auto_20191204_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='補足説明'),
        ),
        migrations.AddField(
            model_name='part',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
    ]
