# Generated by Django 2.1 on 2019-12-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekimei1', '0005_auto_20191205_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
