# Generated by Django 2.1 on 2019-12-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekimei1', '0007_auto_20191206_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
