# Generated by Django 2.1 on 2019-12-06 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekimei1', '0008_auto_20191206_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekimei1.Category', verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='part',
            name='song_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
