# Generated by Django 3.0.2 on 2020-02-11 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekimeidatanew', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='company_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ekimeidatanew.Company', to_field='company_code', verbose_name='事業者コード'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_code',
            field=models.IntegerField(default=0, unique=True, verbose_name='事業者コード'),
        ),
    ]
