# Generated by Django 3.0.2 on 2020-02-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekimeidatanew', '0002_auto_20200212_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='company_code',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='事業者コード'),
        ),
        migrations.AlterField(
            model_name='station',
            name='line_cd_old',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='路線コード（旧）'),
        ),
        migrations.AlterField(
            model_name='station',
            name='pref_cd_old',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='都道府県コード（旧）'),
        ),
        migrations.AlterField(
            model_name='station',
            name='sort_by_company',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='事業者ごとの並び順'),
        ),
        migrations.AlterField(
            model_name='station',
            name='sort_by_line',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='路線ごとの並び順'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_cd_old',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='駅コード（旧）'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_g_cd_old',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='駅グループコード（旧）'),
        ),
    ]
