# Generated by Django 3.0.2 on 2020-02-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekimeidatanew', '0003_auto_20200212_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='e_sort_old',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='並び順（旧）'),
        ),
        migrations.AlterField(
            model_name='station',
            name='e_status_old',
            field=models.IntegerField(blank=True, choices=[(0, '運用中'), (1, '運用前'), (2, '廃止')], default=0, null=True, verbose_name='状態（旧）'),
        ),
        migrations.AlterField(
            model_name='station',
            name='sort',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='並び順'),
        ),
    ]
