# Generated by Django 3.0.2 on 2020-02-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekimeidatanew', '0004_auto_20200212_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='railway_type_code_2',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sort_by_railway_type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sort_by_railway_type_code_2',
        ),
        migrations.RemoveField(
            model_name='line',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='line',
            name='railway_type_code_2',
        ),
        migrations.RemoveField(
            model_name='line',
            name='sort_by_railway_type_code_2',
        ),
        migrations.RemoveField(
            model_name='station',
            name='company_code',
        ),
        migrations.RemoveField(
            model_name='station',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='station',
            name='line_cd_old',
        ),
        migrations.RemoveField(
            model_name='station',
            name='railway_type_code_2',
        ),
        migrations.RemoveField(
            model_name='station',
            name='sort_by_company',
        ),
        migrations.RemoveField(
            model_name='station',
            name='sort_by_railway_type_code_2',
        ),
        migrations.RemoveField(
            model_name='station',
            name='station_cd_old',
        ),
        migrations.RemoveField(
            model_name='station',
            name='station_g_cd_old',
        ),
        migrations.AddField(
            model_name='company',
            name='company_name_short_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='事業者名（愛称2）'),
        ),
        migrations.AddField(
            model_name='line',
            name='line_name_sub',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='路線区別名'),
        ),
    ]
