# Generated by Django 3.0.2 on 2020-02-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekimeidatanew', '0007_auto_20200218_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationservice',
            name='numbering_head',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ナンバリング接頭辞'),
        ),
        migrations.AddField(
            model_name='stationservice',
            name='numbering_middle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ナンバリングハイフン'),
        ),
    ]
