# Generated by Django 3.0.2 on 2020-02-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekimeidatanew', '0008_auto_20200220_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='area_code',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='地域'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='会社色'),
        ),
        migrations.AddField(
            model_name='company',
            name='sort_by_area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地域ごとの並び順'),
        ),
        migrations.AddField(
            model_name='lineservice',
            name='line_color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='路線カラー'),
        ),
        migrations.AddField(
            model_name='stationservice',
            name='station_color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='駅カラー'),
        ),
    ]
